version: '3'
services:
  ubuntu:
    image: ${RUN_IMAGE}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        ANSIBLE_VERSION: ${ANSIBLE_VERSION}
    #environment:
    #  ENV: beta
    command: bash
    tty: true
    container_name: ubuntu
    hostname: docker-ubuntu
    restart: unless-stopped
    env_file:
      - ./envfile/${ENV}.env
